Logged in as
MechaMåsen
552037676597903371
------
  File "bot.py", line 7
    async def on_ready():
        ^
SyntaxError: invalid syntax
Logged in as
MechaMåsen
552037676597903371
------
Ignoring exception in command kingen
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 367, in invoke
    yield from self.prepare(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 345, in prepare
    yield from self._parse_arguments(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 304, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 212, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.
Ignoring exception in command kingen
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 367, in invoke
    yield from self.prepare(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 345, in prepare
    yield from self._parse_arguments(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 304, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 212, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "on_ready" is not found
Logged in as
MechaMåsen
552037676597903371
------
Ignoring exception in command kingen
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 367, in invoke
    yield from self.prepare(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 345, in prepare
    yield from self._parse_arguments(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 304, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 212, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "cool" is not found
Logged in as
MechaMåsen
552037676597903371
------
Ignoring exception in command kingen
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 367, in invoke
    yield from self.prepare(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 345, in prepare
    yield from self._parse_arguments(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 304, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 212, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.
Logged in as
MechaMåsen
552037676597903371
------
  File "bot.py", line 15
    await ctx.send(":smiley: :wave: Hello, there!")
        ^
IndentationError: expected an indented block
  File "bot.py", line 15
    await ctx.send(":smiley: :wave: Hello, there!")
        ^
IndentationError: expected an indented block
Logged in as
MechaMåsen
552037676597903371
------
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0f80869d30>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f0f80733288>, 149706.828576554)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f0f80869d68>
Task was destroyed but it is pending!
task: <Task pending coro=<DiscordWebSocket.close_connection() running at /usr/lib/python3.6/site-packages/discord/gateway.py:539> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f0f8085dc18>()]> cb=[shield.<locals>._done_callback() at /usr/lib64/python3.6/asyncio/tasks.py:688]>
Task was destroyed but it is pending!
task: <Task pending coro=<BotBase.close() running at /usr/lib/python3.6/site-packages/discord/ext/commands/bot.py:210> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f0f8085d4c8>()]> cb=[Client._do_cleanup.<locals>.when_future_is_done() at /usr/lib/python3.6/site-packages/discord/client.py:498]>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f95f5645e10>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f95f550a2e8>, 149849.530607098)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f95f5645e48>
Task was destroyed but it is pending!
task: <Task pending coro=<DiscordWebSocket.close_connection() running at /usr/lib/python3.6/site-packages/discord/gateway.py:539> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f95f5639c18>()]> cb=[shield.<locals>._done_callback() at /usr/lib64/python3.6/asyncio/tasks.py:688]>
Task was destroyed but it is pending!
task: <Task pending coro=<ConnectionState._delay_ready() running at /usr/lib/python3.6/site-packages/discord/state.py:296> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f95f5639d38>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<BotBase.close() running at /usr/lib/python3.6/site-packages/discord/ext/commands/bot.py:210> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f95f5639c48>()]> cb=[Client._do_cleanup.<locals>.when_future_is_done() at /usr/lib/python3.6/site-packages/discord/client.py:498]>
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "factorio" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "factorio" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "commands" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "commands" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "factorio" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "commands" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "factorio" is not found
Logged in as
MechaMåsen
552037676597903371
------
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f87c14c8ba8>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f87c1388f48>, 149866.454773769)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f87c14c8be0>
Task was destroyed but it is pending!
task: <Task pending coro=<DiscordWebSocket.close_connection() running at /usr/lib/python3.6/site-packages/discord/gateway.py:539> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f87c14bca08>()]> cb=[shield.<locals>._done_callback() at /usr/lib64/python3.6/asyncio/tasks.py:688]>
Task was destroyed but it is pending!
task: <Task pending coro=<BotBase.close() running at /usr/lib/python3.6/site-packages/discord/ext/commands/bot.py:210> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f87c14bce88>()]> cb=[Client._do_cleanup.<locals>.when_future_is_done() at /usr/lib/python3.6/site-packages/discord/client.py:498]>
Logged in as
MechaMåsen
552037676597903371
------
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f38de939e80>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f38de7fd2e8>, 175281.207418164)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f38de939eb8>
Task was destroyed but it is pending!
task: <Task pending coro=<DiscordWebSocket.close_connection() running at /usr/lib/python3.6/site-packages/discord/gateway.py:539> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f38de92ec48>()]> cb=[shield.<locals>._done_callback() at /usr/lib64/python3.6/asyncio/tasks.py:688]>
Task was destroyed but it is pending!
task: <Task pending coro=<BotBase.close() running at /usr/lib/python3.6/site-packages/discord/ext/commands/bot.py:210> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f38de92ee58>()]> cb=[Client._do_cleanup.<locals>.when_future_is_done() at /usr/lib/python3.6/site-packages/discord/client.py:498]>
   0.000 2019-03-11 09:31:46; Factorio 0.17.9 (build 43513, linux64, headless)
   0.000 Operating system: Linux
   0.000 Program arguments: "/opt/factorio/bin/x64/factorio" "--start-server" "/opt/factorio/saves/servermap.zip" "--server-settings" "/opt/factorio/data/server-settings.json" "--executable-path" "/opt/factorio/bin/x64/factorio" 
   0.000 Read data path: /opt/factorio/data
   0.000 Write data path: /opt/factorio [22842/25588MB]
   0.000 Binaries path: /opt/factorio/bin
   0.008 System info: [CPU: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, 1 core, RAM: 991 MB]
   0.008 Environment: DISPLAY=<unset>, WAYLAND_DISPLAY=<unset>
   0.008 Running in headless mode
   0.012 Loading mod core 0.0.0 (data.lua)
   0.061 Loading mod base 0.17.9 (data.lua)
   0.284 Loading mod base 0.17.9 (data-updates.lua)
   0.371 Checksum for core: 2736929835
   0.371 Checksum of base: 3535299958
   0.895 Info PlayerData.cpp:67: Local player-data.json available, timestamp 1552296700
   0.895 Info PlayerData.cpp:74: Cloud player-data.json unavailable
   0.896 Custom inputs active: 0
   0.897 Factorio initialised
   0.898 Info HttpSharedState.cpp:54: Downloading https://auth.factorio.com/api-login?api_version=2
   3.814 Info AuthServerConnector.cpp:172: Got token from auth server for username(Moezenka).
   3.817 Info ServerSynchronizer.cpp:29: nextHeartbeatSequenceNumber(0) initialized Synchronizer nextTickClosureTick(0).
   3.817 Info ServerMultiplayerManager.cpp:714: updateTick(4294967295) changing state from(Ready) to(PreparedToHostGame)
   3.817 Info ServerMultiplayerManager.cpp:714: updateTick(4294967295) changing state from(PreparedToHostGame) to(CreatingGame)
   3.821 Loading map /opt/factorio/saves/servermap.zip: 895400 bytes.
   3.857 Loading Level.dat: 1254444 bytes.
   3.874 Info Scenario.cpp:147: Map version 0.17.9-1
   3.935 Loading script.dat: 328 bytes.
   3.942 Checksum for script /opt/factorio/temp/currently-playing/control.lua: 1848333929
   3.946 Info UDPSocket.cpp:27: Opening socket at (IP ADDR:({0.0.0.0:34197}))
   3.946 Hosting game at IP ADDR:({0.0.0.0:34197})
   3.947 Info HttpSharedState.cpp:54: Downloading https://auth.factorio.com/generate-server-padlock-2
   4.077 Info AuthServerConnector.cpp:109: Obtained serverPadlock for serverHash (GbU6AbmHUtRq88yqXOsFah1qTomvj2La) from the auth server.
   4.077 Info ServerMultiplayerManager.cpp:714: updateTick(163) changing state from(CreatingGame) to(InGame)
   4.091 Info ServerRouter.cpp:606: Asking pingpong servers (pingpong1.factorio.com:34197, pingpong2.factorio.com:34197, pingpong3.factorio.com:34197, pingpong4.factorio.com:34197) for own address
   4.091 Info UDPSocket.cpp:39: Opening socket for broadcast
   4.112 Error InterruptibleStdioStream.cpp:54: Reading stdin failed
   4.183 Info ServerRouter.cpp:485: Own address is IP ADDR:({134.209.89.97:34197}) (confirmed by pingpong1)
   4.219 Info ServerRouter.cpp:485: Own address is IP ADDR:({134.209.89.97:34197}) (confirmed by pingpong3)
   4.338 Info ServerRouter.cpp:485: Own address is IP ADDR:({134.209.89.97:34197}) (confirmed by pingpong4)
   4.587 Info MatchingServer.cpp:86: Matching server game `4651754` has been created.
   4.590 Info ServerMultiplayerManager.cpp:643: Matching server connection resumed
 210.988 ConnectionRequestReplyConfirm (type(ConnectionRequestReplyConfirm) ) from(IP ADDR:({188.151.3.151:61306}))
 210.988 Refusing connection for address (IP ADDR:({188.151.3.151:61306})), username (Moezenka). UserVerificationMissing
 211.645 ConnectionRequestReplyConfirm (type(ConnectionRequestReplyConfirm) ) from(IP ADDR:({188.151.3.151:64680}))
 211.645 Refusing connection for address (IP ADDR:({188.151.3.151:64680})), username (Moezenka). PasswordMissing
 211.881 Warning TransmissionControlHelper.cpp:179: Fragment 0001 failed too many times
 212.504 Warning TransmissionControlHelper.cpp:179: Fragment 0003 failed too many times
 212.504 Warning TransmissionControlHelper.cpp:179: Fragment 0004 failed too many times
 212.504 Warning TransmissionControlHelper.cpp:179: Fragment 0005 failed too many times
 212.538 Warning TransmissionControlHelper.cpp:179: Fragment 0006 failed too many times
 214.254 ConnectionRequestReplyConfirm (type(ConnectionRequestReplyConfirm) ) from(IP ADDR:({188.151.3.151:51203}))
 214.254 Info ServerRouter.cpp:418: Replying to connectionRequest for address(IP ADDR:({188.151.3.151:51203})).
 214.254 Info ServerSynchronizer.cpp:557: nextHeartbeatSequenceNumber(6243) adding peer(1)
 214.272 Info ServerMultiplayerManager.cpp:714: updateTick(163) changing state from(InGame) to(InGameSavingMap)
 214.305 Info ServerMultiplayerManager.cpp:813: updateTick(163) received stateChanged peerID(1) oldState(Ready) newState(ConnectedWaitingForMap)
 214.374 Info ServerMultiplayerManager.cpp:876: UpdateTick(163) Serving map(/opt/factorio/temp/mp-save-0.zip) for peer(1) size(895400) crc(4047623571)
 214.374 Info ServerMultiplayerManager.cpp:714: updateTick(163) changing state from(InGameSavingMap) to(InGame)
 214.441 Info ServerMultiplayerManager.cpp:813: updateTick(163) received stateChanged peerID(1) oldState(ConnectedWaitingForMap) newState(ConnectedDownloadingMap)
 214.744 Info ServerMultiplayerManager.cpp:813: updateTick(163) received stateChanged peerID(1) oldState(ConnectedDownloadingMap) newState(ConnectedLoadingMap)
 215.118 Info ServerMultiplayerManager.cpp:813: updateTick(185) received stateChanged peerID(1) oldState(ConnectedLoadingMap) newState(TryingToCatchUp)
 215.153 Info ServerMultiplayerManager.cpp:813: updateTick(187) received stateChanged peerID(1) oldState(TryingToCatchUp) newState(WaitingForCommandToStartSendingTickClosures)
 215.154 Info GameActionHandler.cpp:4013: UpdateTick (187) processed PlayerJoinGame peerID(1) playerIndex(0) mode(connect) 
 215.239 Info ServerMultiplayerManager.cpp:813: updateTick(192) received stateChanged peerID(1) oldState(WaitingForCommandToStartSendingTickClosures) newState(InGame)
2019-03-11 09:35:22 [JOIN] Moezenka joined the game
 231.530 Info ServerMultiplayerManager.cpp:922: Disconnect notification for peer (1)
 231.530 Info ServerMultiplayerManager.cpp:813: updateTick(1170) received stateChanged peerID(1) oldState(InGame) newState(DisconnectScheduled)
2019-03-11 09:35:38 [LEAVE] Moezenka left the game
 231.531 Info ServerSynchronizer.cpp:576: nextHeartbeatSequenceNumber(6746) removing peer(1).
 232.541 Info ServerMultiplayerManager.cpp:1063: Auto saving map as /opt/factorio/saves/servermap.zip
 232.541 Info AppManager.cpp:374: Saving game as /opt/factorio/saves/servermap.zip
 232.641 Info AppManagerStates.cpp:1716: Saving finished
3359.693 Received SIGTERM, shutting down
3359.693 Quitting: signal.
3359.693 Info MainLoop.cpp:389: Saving map as /opt/factorio/saves/servermap.zip
3359.703 Received SIGHUP, shutting down
Logged in as
MechaMåsen
552037676597903371
------
3359.887 Info MainLoop.cpp:400: Saving progress: 0.232558%
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fdf36fd2e80>
Task was destroyed but it is pending!
task: <Task pending coro=<DiscordWebSocket.close_connection() running at /usr/lib/python3.6/site-packages/discord/gateway.py:539> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fdf36fc2798>()]> cb=[shield.<locals>._done_callback() at /usr/lib64/python3.6/asyncio/tasks.py:688]>
Task was destroyed but it is pending!
task: <Task pending coro=<BotBase.close() running at /usr/lib/python3.6/site-packages/discord/ext/commands/bot.py:210> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fdf36fc2e88>()]> cb=[Client._do_cleanup.<locals>.when_future_is_done() at /usr/lib/python3.6/site-packages/discord/client.py:498]>
3359.969 Info MainLoop.cpp:400: Saving progress: 100.000000%
3360.061 Info ServerMultiplayerManager.cpp:114: Disconnecting multiplayer connection.
3360.061 Info ServerMultiplayerManager.cpp:714: updateTick(1171) changing state from(InGame) to(DisconnectingScheduled)
3360.095 Info ServerMultiplayerManager.cpp:714: updateTick(1171) changing state from(DisconnectingScheduled) to(Disconnecting)
3360.128 Info ServerMultiplayerManager.cpp:714: updateTick(1171) changing state from(Disconnecting) to(Disconnected)
3360.128 Info ServerMultiplayerManager.cpp:138: Quitting multiplayer connection.
3360.128 Info ServerMultiplayerManager.cpp:714: updateTick(1171) changing state from(Disconnected) to(Closed)
3360.145 Info HttpSharedState.cpp:54: Downloading https://multiplayer.factorio.com/remove-game/4651754
3360.247 Info UDPSocket.cpp:210: Closing socket
3360.247 Info UDPSocket.cpp:240: Socket closed
3360.247 Info UDPSocket.cpp:210: Closing socket
3360.247 Info GlobalContext.cpp:678: Waiting for child processes to exit: 
3360.346 Info UDPSocket.cpp:210: Closing socket
3360.346 Info UDPSocket.cpp:240: Socket closed
3360.372 Goodbye
   0.001 2019-03-11 11:04:25; Factorio 0.17.9 (build 43513, linux64, headless)
   0.002 Operating system: Linux
   0.002 Program arguments: "/opt/factorio/bin/x64/factorio" "--start-server" "/opt/factorio/saves/servermap.zip" "--server-settings" "/opt/factorio/data/server-settings.json" "--executable-path" "/opt/factorio/bin/x64/factorio" 
   0.002 Read data path: /opt/factorio/data
   0.002 Write data path: /opt/factorio [22870/25588MB]
   0.002 Binaries path: /opt/factorio/bin
   0.020 System info: [CPU: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, 1 core, RAM: 991 MB]
   0.020 Environment: DISPLAY=<unset>, WAYLAND_DISPLAY=<unset>
   0.020 Running in headless mode
   0.027 Loading mod core 0.0.0 (data.lua)
   0.084 Loading mod base 0.17.9 (data.lua)
   0.382 Loading mod base 0.17.9 (data-updates.lua)
   0.472 Checksum for core: 2736929835
   0.472 Checksum of base: 3535299958
   0.989 Info PlayerData.cpp:67: Local player-data.json available, timestamp 1552300067
   0.989 Info PlayerData.cpp:74: Cloud player-data.json unavailable
   0.997 Custom inputs active: 0
   0.999 Factorio initialised
   1.000 Info HttpSharedState.cpp:54: Downloading https://auth.factorio.com/api-login?api_version=2
   1.925 Info AuthServerConnector.cpp:172: Got token from auth server for username(Moezenka).
   1.926 Info ServerSynchronizer.cpp:29: nextHeartbeatSequenceNumber(0) initialized Synchronizer nextTickClosureTick(0).
   1.926 Info ServerMultiplayerManager.cpp:714: updateTick(4294967295) changing state from(Ready) to(PreparedToHostGame)
   1.926 Info ServerMultiplayerManager.cpp:714: updateTick(4294967295) changing state from(PreparedToHostGame) to(CreatingGame)
   1.946 Loading map /opt/factorio/saves/servermap.zip: 918755 bytes.
   2.370 Loading Level.dat: 1302989 bytes.
   2.389 Info Scenario.cpp:147: Map version 0.17.9-1
   2.445 Loading script.dat: 328 bytes.
   2.459 Checksum for script /opt/factorio/temp/currently-playing/control.lua: 1848333929
   2.471 Info UDPSocket.cpp:27: Opening socket at (IP ADDR:({0.0.0.0:34197}))
   2.472 Hosting game at IP ADDR:({0.0.0.0:34197})
   2.472 Info HttpSharedState.cpp:54: Downloading https://auth.factorio.com/generate-server-padlock-2
   2.557 Info AuthServerConnector.cpp:109: Obtained serverPadlock for serverHash (hVFQX1WgBUkSCat3J1yrwUrql8iOJ6Ay) from the auth server.
   2.557 Info ServerMultiplayerManager.cpp:714: updateTick(1171) changing state from(CreatingGame) to(InGame)
   2.575 Info ServerRouter.cpp:606: Asking pingpong servers (pingpong1.factorio.com:34197, pingpong2.factorio.com:34197, pingpong3.factorio.com:34197, pingpong4.factorio.com:34197) for own address
   2.575 Info UDPSocket.cpp:39: Opening socket for broadcast
   2.595 Error InterruptibleStdioStream.cpp:54: Reading stdin failed
   2.664 Info ServerRouter.cpp:485: Own address is IP ADDR:({134.209.89.97:34197}) (confirmed by pingpong1)
   2.699 Info ServerRouter.cpp:485: Own address is IP ADDR:({134.209.89.97:34197}) (confirmed by pingpong3)
   2.818 Info ServerRouter.cpp:485: Own address is IP ADDR:({134.209.89.97:34197}) (confirmed by pingpong4)
   3.100 Info MatchingServer.cpp:86: Matching server game `4652117` has been created.
   3.104 Info ServerMultiplayerManager.cpp:643: Matching server connection resumed
Logged in as
MechaMåsen
552037676597903371
------
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9614290e10>
Task was destroyed but it is pending!
task: <Task pending coro=<DiscordWebSocket.close_connection() running at /usr/lib/python3.6/site-packages/discord/gateway.py:539> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f961427fbe8>()]> cb=[shield.<locals>._done_callback() at /usr/lib64/python3.6/asyncio/tasks.py:688]>
Task was destroyed but it is pending!
task: <Task pending coro=<BotBase.close() running at /usr/lib/python3.6/site-packages/discord/ext/commands/bot.py:210> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f961427fdf8>()]> cb=[Client._do_cleanup.<locals>.when_future_is_done() at /usr/lib/python3.6/site-packages/discord/client.py:498]>
4954.181 Received SIGTERM, shutting down
4954.182 Quitting: signal.
4954.182 Info MainLoop.cpp:389: Saving map as /opt/factorio/saves/servermap.zip
4954.221 Info MainLoop.cpp:400: Saving progress: 0.232558%
4954.233 Info MainLoop.cpp:400: Saving progress: 100.000000%
4954.259 Info ServerMultiplayerManager.cpp:114: Disconnecting multiplayer connection.
4954.259 Info ServerMultiplayerManager.cpp:714: updateTick(1171) changing state from(InGame) to(DisconnectingScheduled)
4954.292 Info ServerMultiplayerManager.cpp:714: updateTick(1171) changing state from(DisconnectingScheduled) to(Disconnecting)
4954.326 Info ServerMultiplayerManager.cpp:714: updateTick(1171) changing state from(Disconnecting) to(Disconnected)
4954.326 Info ServerMultiplayerManager.cpp:138: Quitting multiplayer connection.
4954.326 Info ServerMultiplayerManager.cpp:714: updateTick(1171) changing state from(Disconnected) to(Closed)
4954.342 Info HttpSharedState.cpp:54: Downloading https://multiplayer.factorio.com/remove-game/4652117
4954.429 Info UDPSocket.cpp:210: Closing socket
4954.429 Info UDPSocket.cpp:240: Socket closed
4954.429 Info UDPSocket.cpp:210: Closing socket
4954.430 Info GlobalContext.cpp:678: Waiting for child processes to exit: 
4954.456 Info UDPSocket.cpp:210: Closing socket
4954.456 Info UDPSocket.cpp:240: Socket closed
4954.482 Goodbye
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "play" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "mårten" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "echotext" is not found
Logged in as
MechaMåsen
552037676597903371
------
Logged in as
MechaMåsen
552037676597903371
------
Logged in as
MechaMåsen
552037676597903371
------
Logged in as
MechaMåsen
552037676597903371
------
Logged in as
MechaMåsen
552037676597903371
------
Logged in as
MechaMåsen
552037676597903371
------
Logged in as
MechaMåsen
552037676597903371
------
Logged in as
MechaMåsen
552037676597903371
------
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f696800dfd0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f696413fd08>, 6413507.623630881)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f6967fa5048>
Task was destroyed but it is pending!
task: <Task pending coro=<DiscordWebSocket.close_connection() running at /usr/lib/python3.6/site-packages/discord/gateway.py:539> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6964169f48>()]> cb=[shield.<locals>._done_callback() at /usr/lib64/python3.6/asyncio/tasks.py:688]>
Task was destroyed but it is pending!
task: <Task pending coro=<BotBase.close() running at /usr/lib/python3.6/site-packages/discord/ext/commands/bot.py:210> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6964169c18>()]> cb=[Client._do_cleanup.<locals>.when_future_is_done() at /usr/lib/python3.6/site-packages/discord/client.py:498]>
